# Generated by Django 4.1.2 on 2022-10-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='False', max_length=100, null='False')),
                ('cost_per_item', models.DecimalField(blank='False', decimal_places=2, max_digits=18, null='False')),
                ('quantity_in_stock', models.IntegerField(blank='False', null='False')),
                ('quantity_sold', models.IntegerField(blank='False', null='False')),
                ('sales', models.DecimalField(blank='False', decimal_places=2, max_digits=18, null='False')),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('last_sales_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
